# Generated by Django 4.2.6 on 2023-11-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHBS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
