# Generated by Django 4.2.6 on 2023-11-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHBS', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='special',
        ),
    ]
