# Generated by Django 4.2.6 on 2023-11-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHBS', '0005_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(default='Ontario', max_length=200),
            preserve_default=False,
        ),
    ]
