# Generated by Django 4.2.6 on 2023-12-07 03:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('CHBS', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=False, max_length=128, region=None),
        ),
    ]
