# Generated by Django 4.2.6 on 2023-12-07 04:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('CHBS', '0008_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=False, max_length=128, null=True, region=None),
        ),
    ]
